/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author jefry
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAFC = new javax.swing.JTable();
        btnPartidoAFC = new javax.swing.JButton();
        btnTodosPartidosAFC = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPartidoCONCACAF = new javax.swing.JButton();
        btnTodosPartidosCONCACAF = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnPartidoCONMEBOL = new javax.swing.JButton();
        btnTodosPartidosCONMEBOL = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCAF = new javax.swing.JTable();
        btnTodosPartidosCAF = new javax.swing.JButton();
        btnPartidoCAF = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAFC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Afganistán"},
                {"Arabia Saudí"},
                {"Australia"},
                {"Bahréin"},
                {"Bangladesh"},
                {"Brunéi Darussalam"},
                {"Bután "},
                {"Camboya"},
                {"Chinese Taipei"},
                {"Emiratos Árabes Unidos"},
                {"Filipinas"},
                {"Guam"},
                {"Hong Kong China"},
                {"India "},
                {"Indonesia"},
                {"Irak"},
                {"Japón"},
                {"Jordania"},
                {"Kuwait"},
                {"Laos"},
                {"Líbano"},
                {"Macao"},
                {"Malasia"},
                {"Maldivas"},
                {"Mongolia"},
                {"Myanmar"},
                {"Nepal"},
                {"Omán"},
                {"Pakistán"},
                {"Palestina"},
                {"Qatar"},
                {"RDP de Corea"},
                {"República de Corea"},
                {"República Kirguisa"},
                {"Rl de Irán"},
                {"RP China"},
                {"Singapur"},
                {"Siria "},
                {"Sri Lanka"},
                {"Tailandia"},
                {"Tayikistán"},
                {"Timor Oriental"},
                {"Turkmenistán"},
                {"Uzbekistán"},
                {"Vietnam"},
                {"Yemen"}
            },
            new String [] {
                "Selecciones AFC"
            }
        ));
        jScrollPane1.setViewportView(tblAFC);

        btnPartidoAFC.setBackground(new java.awt.Color(204, 204, 204));
        btnPartidoAFC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPartidoAFC.setText("Partido por Partido");

        btnTodosPartidosAFC.setBackground(new java.awt.Color(204, 204, 204));
        btnTodosPartidosAFC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodosPartidosAFC.setText("Todos los partidos");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPartidoAFC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodosPartidosAFC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnPartidoAFC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnTodosPartidosAFC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(723, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("AFC", jPanel11);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Anguila"},
                {"Antigua y Barbuda"},
                {"Aruba"},
                {"Bahamas"},
                {"Barbados"},
                {"Belice"},
                {"Bermudas"},
                {"Bonaire"},
                {"Canadá"},
                {"Costa Rica"},
                {"Cuba"},
                {"Curazao"},
                {"Dominica"},
                {"El Salvador"},
                {"Estados Unidos"},
                {"Granada"},
                {"Guatemala"},
                {"Guadalupe"},
                {"Guayana"},
                {"Guayana Francesa"},
                {"Haití"},
                {"Honduras"},
                {"Islas Caimán"},
                {"Islas Turcas y Caicos"},
                {"Islas Vírgenes Británicas"},
                {"Islas Vírgenes de los Estados Unidos"},
                {"Jamaica"},
                {"Martinica"},
                {"Mexico"},
                {"Montserrat"},
                {"Nicaragua"},
                {"Panamá"},
                {"Puerto Rico"},
                {"República Dominicana"},
                {"Saint-Martin"},
                {"San Cristóbal y Nieves"},
                {"San Vicente y las Granadinas"},
                {"Santa Lucía"},
                {"Sint Maarten"},
                {"Surinam"},
                {"Trinidad y Tobago "}
            },
            new String [] {
                "Selecciones CONCACAF"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnPartidoCONCACAF.setBackground(new java.awt.Color(204, 204, 204));
        btnPartidoCONCACAF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPartidoCONCACAF.setText("Partido por Partido");
        btnPartidoCONCACAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoCONCACAFActionPerformed(evt);
            }
        });

        btnTodosPartidosCONCACAF.setBackground(new java.awt.Color(204, 204, 204));
        btnTodosPartidosCONCACAF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodosPartidosCONCACAF.setText("Todos los partidos");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTodosPartidosCONCACAF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPartidoCONCACAF))
                .addGap(55, 55, 55))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnPartidoCONCACAF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTodosPartidosCONCACAF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("CONCACAF", jPanel13);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Argentina"},
                {"Bolivia"},
                {"Brasil"},
                {"Chile"},
                {"Colombia"},
                {"Ecuador"},
                {"Paraguay"},
                {"Perú"},
                {"Uruguay"},
                {null}
            },
            new String [] {
                "Selecciones CONMEBOL"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        btnPartidoCONMEBOL.setBackground(new java.awt.Color(204, 204, 204));
        btnPartidoCONMEBOL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPartidoCONMEBOL.setText("Partidos por Partido");

        btnTodosPartidosCONMEBOL.setBackground(new java.awt.Color(204, 204, 204));
        btnTodosPartidosCONMEBOL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodosPartidosCONMEBOL.setText("Todos los partidos");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPartidoCONMEBOL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTodosPartidosCONMEBOL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnPartidoCONMEBOL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTodosPartidosCONMEBOL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(776, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("CONMEBOL", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("OFC", jPanel16);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("UEFA", jPanel17);

        tblCAF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Angola"},
                {"Argelia"},
                {"Benín"},
                {"Botsuana"},
                {"Burkina Faso"},
                {"Burundi"},
                {"Cabo Verde"},
                {"Camerún"},
                {"Chad"},
                {"Comoras"},
                {"Congo"},
                {"Costa de Marfil"},
                {"Egipto"},
                {"Eritrea"},
                {"Esuatini"},
                {"Etiopía"},
                {"Gabón"},
                {"Gambia"},
                {"Ghana"},
                {"Guinea"},
                {"Guinea Ecuatorial"},
                {"Guinea-Bissáu"},
                {"Kenia"},
                {"Lesoto"},
                {"Liberia"},
                {"Libia"},
                {"Madagascar"},
                {"Malaui"},
                {"Mali"},
                {"Marruecos"},
                {"Mauricio"},
                {"Mauritania"},
                {"Mozambique"},
                {"Namibia"},
                {"Níger"},
                {"Nigeria"},
                {"RD del Congo"},
                {"República Centroafricana"},
                {"Ruanda"},
                {"Santo Tomé y Príncipe"},
                {"Senegal"},
                {"Seychelles"},
                {"Sierra Leona"},
                {"Somalia"},
                {"Sudáfrica"},
                {"Sudán"},
                {"Sudán del Sur"},
                {"Tanzania"},
                {"Togo"},
                {"Túnez"},
                {"Uganda"},
                {"Yibuti"},
                {"Zambia"},
                {null}
            },
            new String [] {
                "Selecciones CAF"
            }
        ));
        jScrollPane2.setViewportView(tblCAF);

        btnTodosPartidosCAF.setBackground(new java.awt.Color(204, 204, 204));
        btnTodosPartidosCAF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodosPartidosCAF.setText("Todos los Partidos");
        btnTodosPartidosCAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosPartidosCAFActionPerformed(evt);
            }
        });

        btnPartidoCAF.setBackground(new java.awt.Color(204, 204, 204));
        btnPartidoCAF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPartidoCAF.setText("Partido por Partido");
        btnPartidoCAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoCAFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPartidoCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTodosPartidosCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnPartidoCAF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTodosPartidosCAF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("CAF", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodosPartidosCAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosPartidosCAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodosPartidosCAFActionPerformed

    private void btnPartidoCAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoCAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPartidoCAFActionPerformed

    private void btnPartidoCONCACAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoCONCACAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPartidoCONCACAFActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPartidoAFC;
    private javax.swing.JButton btnPartidoCAF;
    private javax.swing.JButton btnPartidoCONCACAF;
    private javax.swing.JButton btnPartidoCONMEBOL;
    private javax.swing.JButton btnTodosPartidosAFC;
    private javax.swing.JButton btnTodosPartidosCAF;
    private javax.swing.JButton btnTodosPartidosCONCACAF;
    private javax.swing.JButton btnTodosPartidosCONMEBOL;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblAFC;
    private javax.swing.JTable tblCAF;
    // End of variables declaration//GEN-END:variables
}
